apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test1  # Name of the EKS Cluster
  region: us-west-1
fargateProfiles:
  - name: fargate_profile-1
    selectors:
      # scheduled onto Fargate:
      - namespace: ns-fargate-1 #all in this namespace
  - name: fargate_profile-2
    selectors:
      # label selectors will be scheduled onto Fargate:
      - namespace: ns-fargate-1 # all in this namespace
        labels:
          runon: fargate # all the objects that have this label would run on fargate