apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: aws
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true" # use application load balancer
spec:
  controller: ingress.k8s.aws/alb